apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoupload
  labels:
    app: videoupload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: videoupload-app1
  template:
    metadata:
      labels:
        app: videoupload-app1
    spec:
      containers:
        - name: videoupload-app
          image: us.gcr.io/project2-382721/vid_upload_service
          ports:
            - name: http
              containerPort: 8080