apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-app1
  template:
    metadata:
      labels:
        app: auth-app1
    spec:
      containers:
        - name: auth-app
          image: us.gcr.io/project2-382721/auth_service
          ports:
            - name: http
              containerPort: 8110