apiVersion: v1
kind: Service
metadata:
  name: videostreaming-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8100
    targetPort: 8100
  # loadBalancerIp:
  #   - 35.194.44.119
  selector:
    app: videostreaming