apiVersion: v1
kind: Service
metadata:
  name: videoupload-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  # loadBalancerIp:
  #   - 34.121.182.111
  selector:
    app: videoupload